language: android
jdk:
  - openjdk8

android:
  components:
    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-26

script:
  echo "this is my game" > mygame.jar

after_script:
  chmod +x deploy.sh && ./deploy.sh
